
- name: Installer pip pour Python 3.11
  become: yes
  shell: curl https://bootstrap.pypa.io/get-pip.py | python3.11

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: python3.11 -m pip
    #virtualenv: "{{ remote_home.stdout }}/{{ ros2_ws }}/venv"

- name: Install requirements
  pip:
    #virtualenv: "{{ remote_home.stdout }}/{{ ros2_ws }}/venv"
    #virtualenv_python: "{{ python_version }}"
    requirements: "{{ remote_home.stdout }}/{{ ros2_ws }}/src/{{ project_ros_dir }}/{{ conf_dir }}/requirements.txt"
    executable: python3.11 -m pip


#- name: Update project librairy in "{{ remote_home.stdout }}/{{ deploy_dir }}/venv"
#  pip:
#    requirements: "{{ remote_home.stdout }}/{{ ros2_ws }}/src/{{ project_ros_dir }}/{{ conf_dir }}/requirements.txt"
#    virtualenv: "{{ remote_home.stdout }}/{{ ros2_ws }}/venv"