---
- name: install didier
  hosts: controller
#  become: yes

  vars_files:
  - vars/main.yml

  roles:
    - role: dir_struct
    - role: synchronise
    - role: packages
    - role: python
    - role: set-bashrc
    - role: ros_humble_base
    - role: ros_humble_desktop
    - role: colcon_build
