---
- name: install didier
  hosts: robot
#  become: yes

  vars_files:
  - vars/main.yml

  roles:
    - role: dir_struct
    - role: synchronise
    - role: packages
    - role: python
      vars:
        project_dir: "{{ ros2_ws }}"
    - role: set-bashrc
    - role: ros_humble_base
    - role: colcon_build
    - role: services
#      vars:
#        project_dir: "{{ local_projects_dir }}/{{ robot_project_dir }}"
#        project_name: "controller"
    #    - packages
#    - blinka

    #- deploy
    #- set-vim
    #- set-bashrc
    #- services
