- name: apt-get update/upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    #garde en cache 24h
    cache_valid_time: 84600

- name: Install packages from {{ local_projects_dir }}/{{ local_project_dir }}/conf/{{ package_file }}
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ lookup('file', '{{ local_projects_dir }}/{{ local_project_dir }}/conf/{{ package_file }}').splitlines() }}"
