# roles/packages/defaults/main.yml
packages_base:
  - ffmpeg
  - python3
  - python3-dev
  - python3-pip
  - python3-venv
  - build-essential
  - libffi-dev
  - pkg-config
  - libcairo2-dev
#  - libssl-dev  -
  - vim
