---
- name: deploy didier
  hosts: robot-test
#  become: yes

  vars_files:
  - vars/main.yml

  tasks:
  - name: Synchronize test directory"
    synchronize:
      src: "{{ local_projects_dir }}/{{ local_project_dir }}/"
      dest: "test/"
      recursive: yes
      copy_links: yes
      rsync_opts:
        - "--verbose"
        - "--exclude=.*"
        #- "--exclude=.git/"
        - "--exclude=.~tmp~/"
        - "--exclude=*tar.gz"
        #- "--exclude=.idea/"
        - "--exclude=__pycache__/"
        - "--exclude=venv/"
        #- "--delete"
        #- "--exclude=.editorconfig"
        #- "--exclude=.gitignore"

        #- "--exclude=robot_bringup/"
        #- "--exclude=robot_interfaces/"
