---
- name: install didier ros controller docker-arm64 image on pios
  hosts: glove-left
#  become: yes

  vars_files:
  - vars/main.yml

  roles:
    - role: dir_struct
      directories:
          - "{{ ros2_ws }}/build"
          - "{{ ros2_ws }}/install"
          - "{{ ros2_ws }}/log"
          - "{{ ros2_ws }}/src/{{ project_ros_dir }}"
    - role: synchronise
      become: yes
    - role: packages
      vars:
      - package_file: "packages-docker.txt"
    - role: download-install-deb-from-url
      vars:
        - debian_packages_urls:
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/containerd.io_1.7.18-1_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce-cli_27.0.1-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce_27.0.1-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-buildx-plugin_0.15.1-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-compose-plugin_2.28.1-1~debian.12~bookworm_arm64.deb"
    #- role: docker-arm64
    - role: set-bashrc
#    - role: screen-config
    - role: desktop_lunch
    #- role: start-scripts
    - role: command_root
      vars:
        command: "reboot"
#    - role: screen-config


