---
- name: deploy {{ target_group | default('robot') }}
  hosts: "{{ target_group | default('robot') }}"
#  become: yes

  vars_files:
  - vars/main.yml

  roles:
    - role: dir_struct
      vars:
      - directories:
          - "{{ ros2_ws }}/build"
          - "{{ ros2_ws }}/install"
          - "{{ ros2_ws }}/log"
          - "{{ ros2_ws }}/src/{{ project_ros_dir }}"
          - "scripts"
    - role: synchronise
    - role: packages
      vars:
      - package_file: "packages.txt"
    - role: download-install-deb-from-url
      vars:
        - debian_packages_urls:
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/containerd.io_1.7.22-1_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce-cli_27.3.1-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce_27.3.1-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-buildx-plugin_0.17.1-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-compose-plugin_2.29.7-1~debian.12~bookworm_arm64.deb"
    #- role: docker-arm64
    - role: logging
    - role: set-bashrc
    - role: start-scripts
    - role: activate-i2c
    - role: services